# Site settings
title: Nico Alfianto
description: Information Systems Student | Data Analyst | System Designer | BI Enthusiast
logo: /assets/img/profile.jpg  # ganti sesuai path foto lo
email: alfiantonico9@gmail.com
url: "https://nico-alfianto.github.io" # ganti sama username.github.io lo
baseurl: "" # kosongin kalo deploy di username.github.io

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
    - jekyll-seo-tag

# Exclude dari proses Jekyll
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor/
    - README.md

# Defaults buat halaman
defaults:
    - scope:
      path: ""
    values:
      layout: "default"

# Social links buat jekyll-seo-tag
social:
  name: Nico Alfianto
  links:
        - https://github.com/nico-alfianto
        - https://www.linkedin.com/in/nico-alfianto
