title: Nico Alfianto

logo: /images/nico.jpg

description: >
  Information Systems Student<br>
  Data Analytics & BI Enthusiast<br>
  BNSP Certified DBA<br><br>
  <a href="https://www.linkedin.com/in/nico-alfianto">LinkedIn</a> |
  <a href="https://github.com/nico-alfianto">GitHub</a>

remote_theme: pages-themes/minimal@v0.2.0

plugins:
- jekyll-remote-theme

google_analytics:
